/**
 * Bundle data generator.
 * Reads an Elasticsearch diagnostic bundle from disk, parses it, and writes
 * src/generated/bundleData.ts for the static React app to import.
 *
 * Usage:
 *   npm run generate -- --customer <dirname> --name "Customer Name" [--notes "text"]
 *
 * The <dirname> must be a folder inside diagnostics/ containing:
 *   api-diagnostics-YYYYMMDD/         (required)
 *   kibana-api-diagnostics-YYYYMMDD/  (optional)
 */
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs'
import { join, relative } from 'node:path'
import { parseBundle } from '../src/parsers/index.ts'
import type { BundleData } from '../src/utils/bundleReader.ts'

function getArg(flag: string): string | undefined {
  const idx = process.argv.indexOf(flag)
  return idx !== -1 && idx + 1 < process.argv.length ? process.argv[idx + 1] : undefined
}

const customerDir = getArg('--customer')
const customerName = getArg('--name')
const clusterName = getArg('--cluster') ?? null
const notes = getArg('--notes') ?? null

if (!customerDir || !customerName) {
  console.error('Usage: npm run generate -- --customer <dirname> --name "Customer Name" [--cluster "Cluster Name"] [--notes "text"]')
  process.exit(1)
}

const root = process.cwd()
const customerPath = join(root, 'diagnostics', customerDir)

let entries: string[]
try {
  entries = readdirSync(customerPath)
} catch {
  console.error(`Error: diagnostics/${customerDir}/ not found`)
  process.exit(1)
}

const isDir = (name: string) => {
  try { return statSync(join(customerPath, name)).isDirectory() } catch { return false }
}

const esBundleName = entries.find(e => e.startsWith('api-diagnostics-') && isDir(e))
const kibanaBundleName = entries.find(e => e.startsWith('kibana-api-diagnostics-') && isDir(e))

if (!esBundleName) {
  console.error(`Error: No api-diagnostics-* folder found in diagnostics/${customerDir}/`)
  process.exit(1)
}

function readDirRecursive(dir: string): Map<string, string> {
  const files = new Map<string, string>()
  const recurse = (current: string) => {
    for (const name of readdirSync(current)) {
      const full = join(current, name)
      const rel = relative(dir, full)
      try {
        if (statSync(full).isDirectory()) {
          recurse(full)
        } else {
          files.set(rel, readFileSync(full, 'utf-8'))
        }
      } catch {
        // skip unreadable or binary files
      }
    }
  }
  recurse(dir)
  return files
}

const esBundlePath = join(customerPath, esBundleName)
const files = readDirRecursive(esBundlePath)

console.log(`Reading ${files.size} files from ${esBundleName}...`)

const bundleData: BundleData = { files, rootName: esBundleName }
const model = await parseBundle(bundleData)

const output = {
  model,
  customerName,
  clusterName,
  notes,
  generatedAt: new Date().toISOString(),
  hasKibanaBundle: Boolean(kibanaBundleName),
}

const outDir = join(root, 'src', 'generated')
mkdirSync(outDir, { recursive: true })

// Write build config so vite.config.ts can set the correct output directory
const pageTitle = clusterName
  ? `${customerName} — ${clusterName}`
  : customerName
writeFileSync(
  join(outDir, 'buildConfig.json'),
  JSON.stringify({ customerDir, pageTitle }, null, 2),
  'utf-8'
)

const outPath = join(outDir, 'bundleData.ts')
const fileContent = [
  '// AUTO-GENERATED by `npm run generate` — do not edit manually',
  '// Contains customer data — do not commit or push',
  '',
  `export const bundleData = ${JSON.stringify(output, null, 2)}`,
  '',
].join('\n')

writeFileSync(outPath, fileContent, 'utf-8')

console.log(`\n✓ Generated src/generated/bundleData.ts`)
console.log(`  Customer : ${customerName}`)
console.log(`  ES bundle: ${esBundleName}`)
console.log(`  Kibana   : ${kibanaBundleName ?? 'not found (optional)'}`)
console.log(`  Notes    : ${notes ?? '(none)'}`)
console.log(`\nNext step: npm run build`)
